In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib
%matplotlib inline

import matplotlib.pyplot as plt
sns.set(style = "whitegrid") #font_scale = 1.3)

from IPython.display import set_matplotlib_formats

import warnings
warnings.filterwarnings("ignore")


# Mac OS를 이용하고 있기 떄문에 AppleGothic을 설정했습니다.
# 윈도우의 경우 다른 폰트를 사용해주셔야 합니다. 나눔폰트가 있는 경우 'NanumGothic' 없는 경우에는 'Malgun Gothic'을 사용해주세요.
# matplotlib.rc('font', family='AppleGothic')
matplotlib.rc('font', family='Malgun Gothic')

# 폰트를 바꿀 경우 마이너스가 표시되지 않는 경우도 있는데 이를 막아주는 코드입니다.
matplotlib.rc('axes', unicode_minus=False)
matplotlib.rcParams['axes.unicode_minus'] = False

# retina 옵션을 통해 해상도를 올립니다.
set_matplotlib_formats('retina')

# 화면에 출력하는 데이터 프레임의 최대 row 수를 500으로 설정합니다.
pd.set_option('display.max_rows', 500)

# 화면에 출력하는 데이터 프레임의 최대 column 수를 500으로 설정합니다.
pd.set_option('display.max_columns', 500)

In [2]:
df1 = pd.read_csv('data/train_kangnam.csv', encoding = 'euc-kr', index_col = [0])
df1

         gu dong  gu_real_mean  강남과의 거리  kangnam  transaction_real_price
0       종로구  신교동  48968.885914   13.473       13                   37500
1       종로구  필운동  48968.885914   13.473       13                   20000
2       종로구  필운동  48968.885914   13.473       13                   38500
3       종로구  내수동  48968.885914   13.473       13                  118000
4       종로구  내수동  48968.885914   13.473       13                  120000
...     ...  ...           ...      ...      ...                     ...
742280  강동구  강일동  46180.322386    9.214        6                   53000
742281  강동구  강일동  46180.322386    9.214        6                   53000
742282  강동구  강일동  46180.322386    9.214        6                   56500
742283  강동구  강일동  46180.322386    9.214        6                   55500
742284  강동구  강일동  46180.322386    9.214        6                   63750

[742285 rows x 6 columns]

In [3]:
train = pd.read_csv('data/real_train.csv', encoding = 'euc-kr', index_col = [0])
train

,gu,dong,exclusive_use_area,year_of_completion,floor,transaction_real_price,hanriver,transaction_year,hakgun,exclusive_use_area_group,hakgun_rank,year_of_completion_group,dep_shop,park_gaesu,pop,gu_area,diff_year,rebuilding,river_re,gu_real_mean,강남과의 거리,kangnam
0,종로구,신교동,84.82,2002,2,37500,0,2008,5,2,2,2000,0,2,179754,23.91,6,0,1,48968.885914,13.473,13
1,종로구,필운동,99.17,1973,6,20000,0,2008,5,3,2,1970,0,3,179754,23.91,35,1,2,48968.885914,13.473,13
2,종로구,필운동,84.74,2007,6,38500,0,2008,5,2,2,2000,0,2,179754,23.91,1,0,1,48968.885914,13.473,13
3,종로구,내수동,146.39,2003,15,118000,0,2008,5,4,2,2000,0,3,179754,23.91,5,0,1,48968.885914,13.473,13
4,종로구,내수동,146.39,2003,15,118000,0,2008,5,4,2,2000,0,3,179754,23.91,5,0,1,48968.885914,13.473,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8540048,노원구,상계동,59.82,1997,8,20000,0,2015,4,1,11,1990,2,2,578221,35.44,18,0,1,29212.908481,17.736,19
8540049,노원구,상계동,59.82,1997,8,20000,0,2015,4,1,11,1990,2,2,578221,35.44,18,0,1,29212.908481,17.736,19
8540050,노원구,상계동,59.82,1997,8,20000,0,2015,4,1,11,1990,2,2,578221,35.44,18,0,1,29212.908481,17.736,19
8540051,노원구,상계동,59.82,1997,8,20000,0,2015,4,1,11,1990,2,2,578221,35.44,18,0,1,29212.908481,17.736,19
8540052,노원구,상계동,59.82,1997,8,20000,0,2015,4,1,11,1990,2,2,578221,35.44,18,0,1,29212.908481,17.736,19

In [4]:
train = pd.merge(train,df1,on=['gu', 'dong', 'transaction_real_price'], how='outer')
train.head()

MemoryError: Unable to allocate 9.32 GiB for an array with shape (1250629503,) and data type int64

In [ ]:
train.to_csv('data/real_train.csv', encoding = 'euc-kr')