In [77]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib
%matplotlib inline

import matplotlib.pyplot as plt
sns.set(style = "whitegrid") #font_scale = 1.3)

from IPython.display import set_matplotlib_formats

import warnings
warnings.filterwarnings("ignore")


# Mac OS를 이용하고 있기 떄문에 AppleGothic을 설정했습니다.
# 윈도우의 경우 다른 폰트를 사용해주셔야 합니다. 나눔폰트가 있는 경우 'NanumGothic' 없는 경우에는 'Malgun Gothic'을 사용해주세요.
# matplotlib.rc('font', family='AppleGothic')
matplotlib.rc('font', family='Malgun Gothic')

# 폰트를 바꿀 경우 마이너스가 표시되지 않는 경우도 있는데 이를 막아주는 코드입니다.
matplotlib.rc('axes', unicode_minus=False)
matplotlib.rcParams['axes.unicode_minus'] = False

# retina 옵션을 통해 해상도를 올립니다.
set_matplotlib_formats('retina')

# 화면에 출력하는 데이터 프레임의 최대 row 수를 500으로 설정합니다.
pd.set_option('display.max_rows', 500)

# 화면에 출력하는 데이터 프레임의 최대 column 수를 500으로 설정합니다.
pd.set_option('display.max_columns', 500)

In [142]:
train = pd.read_csv('data/real_train.csv', index_col = [0], encoding = 'euc-kr')
train.head()

# a = []
# b = []
# c = []
# for i in train['gu'].unique():
#     a.append(train.loc[train['gu'] == i]['transaction_real_price'].median())
#     b.append(train.loc[train['gu'] == i]['transaction_real_price'].mean())
#     c.append(i)
# asd = pd.DataFrame(b, c)
# asd.sort_values(by = [0], ascending = False)

,gu,dong,apartment_id,apt,exclusive_use_area,year_of_completion,floor,transaction_real_price,hanriver,transaction_year,hakgun,exclusive_use_area_group,hakgun_rank,year_of_completion_group,park_gaesu,pop,gu_area,diff_year,rebuilding,river_re,gu_mean,apt_age_group,dep_shop,강남과의 거리,kangnam
0,송파구,가락동,7155,시영1,51.40,1980,4,69000,0,2008,6,1,3,1980,0,676580,33.88,28,0,1,69447,20,1,4.354,2
1,송파구,가락동,7155,시영1,40.09,1980,5,55000,0,2008,6,1,3,1980,0,676580,33.88,28,0,1,69447,20,1,4.354,2
2,송파구,가락동,520,가락(1차)쌍용아파트,84.69,1997,1,52500,0,2008,6,2,3,1990,0,676580,33.88,11,0,1,69447,10,1,4.354,2
3,송파구,가락동,533,가락한일유앤아이,100.95,2003,7,39500,0,2008,6,3,3,2000,1,676580,33.88,5,0,1,69447,0,1,4.354,2
4,송파구,가락동,7155,시영1,51.40,1980,4,56200,0,2008,6,1,3,1980,0,676580,33.88,28,0,1,69447,20,1,4.354,2

In [ ]:
train

In [151]:
# train.loc[train['gu'] == '강남구']['transaction_real_price'].mean()
# train.loc[train['gu'] == '서초구']['transaction_real_price'].mean()
a = []
b = []
c = []
for i in train['gu'].unique():
    print(i,'중간값', train.loc[train['gu'] == i]['transaction_real_price'].median())
    print(i,'평균값', train.loc[train['gu'] == i]['transaction_real_price'].mean())
    print('')
    a.append(train.loc[train['gu'] == i]['transaction_real_price'].median())
    b.append(train.loc[train['gu'] == i]['transaction_real_price'].mean())
    c.append(i)

송파구 중간값 62500.0
송파구 평균값 69447.39020338787

구로구 중간값 32300.0
구로구 평균값 33589.535633867774

금천구 중간값 28000.0
금천구 평균값 28286.29577347837

강서구 중간값 34000.0
강서구 평균값 36881.131408649686

용산구 중간값 69000.0
용산구 평균값 84635.43404414515

은평구 중간값 36950.0
은평구 평균값 38849.72400525526

강동구 중간값 43000.0
강동구 평균값 46180.32238618378

강남구 중간값 80000.0
강남구 평균값 91418.7200959671

종로구 중간값 42000.0
종로구 평균값 48968.88591426072

마포구 중간값 49000.0
마포구 평균값 52881.136045510684

노원구 중간값 26500.0
노원구 평균값 29212.90848127293

광진구 중간값 52500.0
광진구 평균값 56677.571809548586

성동구 중간값 49000.0
성동구 평균값 52946.757005404994

성북구 중간값 37000.0
성북구 평균값 38026.40540831717

서대문구 중간값 37000.0
서대문구 평균값 39217.82842382395

중구 중간값 50800.0
중구 평균값 53621.843016961386

관악구 중간값 36000.0
관악구 평균값 36149.74561776719

서초구 중간값 83800.0
서초구 평균값 93760.4505476933

동작구 중간값 49300.0
동작구 평균값 50891.52867705118

동대문구 중간값 36900.0
동대문구 평균값 37643.15194388777

영등포구 중간값 40200.0
영등포구 평균값 46139.70625882353

도봉구 중간값 26800.0
도봉구 평균값 28289.35775378989

중랑구 중간값 29950.0
중랑구 평균값 30611.30146839753

양천구 중간값 44000.0
양천구 평균값 50568.22859906497

강북구 중간값 32800.0
강북구 평균값 32846.52388797364

In [155]:
asd = pd.DataFrame(b, c)
asd.sort_values(by = [0], ascending = False)

                 0
서초구   93760.450548
강남구   91418.720096
용산구   84635.434044
송파구   69447.390203
광진구   56677.571810
중구    53621.843017
성동구   52946.757005
마포구   52881.136046
동작구   50891.528677
양천구   50568.228599
종로구   48968.885914
강동구   46180.322386
영등포구  46139.706259
서대문구  39217.828424
은평구   38849.724005
성북구   38026.405408
동대문구  37643.151944
강서구   36881.131409
관악구   36149.745618
구로구   33589.535634
강북구   32846.523888
중랑구   30611.301468
노원구   29212.908481
도봉구   28289.357754
금천구   28286.295773

In [79]:
train[['gu','kangnam', 'gu_mean']].drop_duplicates().sort_values(by = ['gu_mean'], ascending = False)

          gu  kangnam  gu_mean
512104   서초구        1    93760
222204   강남구        0    91419
144563   용산구        5    84635
0        송파구        2    69447
381567   광진구        3    56678
480287    중구        7    53622
396941   성동구        4    52947
280437   마포구       17    52881
549625   동작구        9    50892
691713   양천구       22    50568
274722   종로구       13    48969
179240   강동구        6    46180
602437  영등포구       14    46140
460156  서대문구       15    39218
157928   은평구       21    38850
423028   성북구       12    38026
577487  동대문구        8    37643
100677   강서구       24    36881
488600   관악구       11    36150
51773    구로구       20    33590
728931   강북구       18    32847
668218   중랑구       10    30611
307156   노원구       19    29213
634312   도봉구       23    28289
88634    금천구       16    28286

In [80]:
train['gu'].unique()
train['gu_mean'] = 0
for i in train['gu'].unique():
    train['gu_mean'] = np.where((train['gu'] == i), round(train.loc[train['gu']==i]['transaction_real_price'].mean()), train['gu_mean'])

In [150]:
for i in train['gu'].unique():
    print('--------------------------------------------------------------------------------------------------')
    print(i, '의 거래량                  : ', len(train.loc[train['gu'] == i]))
    print(i, '의 힘                      : ', 100 * len(train.loc[train['gu'] == i]) / len(train)) 
    print(' ')
    for j in np.sort(train['exclusive_use_area_group'].unique()):
        print(i, '아파트 나이 ', j, '의 거래량   : ', len(train.loc[train['gu'] == i].loc[train['exclusive_use_area_group'] == j]))
        print(i, '아파트 나이 ', j, '평균 거래가 : ', train.loc[train['gu'] == i].loc[train['exclusive_use_area_group'] == j]['transaction_real_price'].mean())
        print(i, '아파트 나이 ', j, '의 거래비율 : ', 100 *len(train.loc[train['gu'] == i].loc[train['exclusive_use_area_group'] == j]) / len(train.loc[train['gu'] == i]))
        print('')

--------------------------------------------------------------------------------------------------
송파구 의 거래량                  :  51773
송파구 의 힘                      :  6.974814255979846

송파구 아파트 나이  0 의 거래량   :  3129
송파구 아파트 나이  0 평균 거래가 :  32193.86225631192
송파구 아파트 나이  0 의 거래비율 :  6.043690726826724

송파구 아파트 나이  1 의 거래량   :  13879
송파구 아파트 나이  1 평균 거래가 :  50799.75740327113
송파구 아파트 나이  1 의 거래비율 :  26.80740926737875

송파구 아파트 나이  2 의 거래량   :  24700
송파구 아파트 나이  2 평균 거래가 :  71653.3964777328
송파구 아파트 나이  2 의 거래비율 :  47.70826492573349

송파구 아파트 나이  3 의 거래량   :  7039
송파구 아파트 나이  3 평균 거래가 :  93867.08978548089
송파구 아파트 나이  3 의 거래비율 :  13.595889749483321

송파구 아파트 나이  4 의 거래량   :  3026
송파구 아파트 나이  4 평균 거래가 :  118686.70423000661
송파구 아파트 나이  4 의 거래비율 :  5.844745330577714

--------------------------------------------------------------------------------------------------
구로구 의 거래량                  :  36861
구로구 의 힘                      :  4.965882376715143

구로구 아파트 나이  0 의 거래량   :  2073
구로구 아파트 나이  0 평균 거래가 :  14970.985045827303
구로구 아파트 나이  0 의 거래비율 :  5.623830064295597

구로구 아파트 나이  1 의 거래량   :  13890
구로구 아파트 나이  1 평균 거래가 :  26942.410367170625
구로구 아파트 나이  1 의 거래비율 :  37.68210303572882

구로구 아파트 나이  2 의 거래량   :  17544
구로구 아파트 나이  2 평균 거래가 :  37417.64814181487
구로구 아파트 나이  2 의 거래비율 :  47.59501912590543

구로구 아파트 나이  3 의 거래량   :  2910
구로구 아파트 나이  3 평균 거래가 :  50322.61924398626
구로구 아파트 나이  3 의 거래비율 :  7.894522666232604

구로구 아파트 나이  4 의 거래량   :  444
구로구 아파트 나이  4 평균 거래가 :  67533.55855855856
구로구 아파트 나이  4 의 거래비율 :  1.2045251078375518

--------------------------------------------------------------------------------------------------
금천구 의 거래량                  :  12043
금천구 의 힘                      :  1.6224226543712994

금천구 아파트 나이  0 의 거래량   :  651
금천구 아파트 나이  0 평균 거래가 :  13579.73579109063
금천구 아파트 나이  0 의 거래비율 :  5.405629826455202

금천구 아파트 나이  1 의 거래량   :  4895
금천구 아파트 나이  1 평균 거래가 :  23451.930949948928
금천구 아파트 나이  1 의 거래비율 :  40.64601843394503

금천구 아파트 나이  2 의 거래량   :  5172
금천구 아파트 나이  2 평균 거래가 :  31888.58275328693
금천구 아파트 나이  2 의 거래비율 :  42.946109773312294

금천구 아파트 나이  3 의 거래량   :  1306
금천구 아파트 나이  3 평균 거래가 :  39094.71669218989
금천구 아파트 나이  3 의 거래비율 :  10.84447396828033

금천구 아파트 나이  4 의 거래량   :  19
금천구 아파트 나이  4 평균 거래가 :  54147.36842105263
금천구 아파트 나이  4 의 거래비율 :  0.15776799800714109

--------------------------------------------------------------------------------------------------
강서구 의 거래량                  :  43886
강서구 의 힘                      :  5.912284365169713

강서구 아파트 나이  0 의 거래량   :  5362
강서구 아파트 나이  0 평균 거래가 :  19163.066206639312
강서구 아파트 나이  0 의 거래비율 :  12.218019413936107

강서구 아파트 나이  1 의 거래량   :  14125
강서구 아파트 나이  1 평균 거래가 :  30088.030654867256
강서구 아파트 나이  1 의 거래비율 :  32.185662853757464

강서구 아파트 나이  2 의 거래량   :  19686
강서구 아파트 나이  2 평균 거래가 :  41067.16966372041
강서구 아파트 나이  2 의 거래비율 :  44.85712983639429

강서구 아파트 나이  3 의 거래량   :  4123
강서구 아파트 나이  3 평균 거래가 :  58172.18384671356
강서구 아파트 나이  3 의 거래비율 :  9.394795606799434

강서구 아파트 나이  4 의 거래량   :  590
강서구 아파트 나이  4 평균 거래가 :  72080.20847457627
강서구 아파트 나이  4 의 거래비율 :  1.3443922891127011

--------------------------------------------------------------------------------------------------
용산구 의 거래량                  :  13365
용산구 의 힘                      :  1.8005213630883017

용산구 아파트 나이  0 의 거래량   :  424
용산구 아파트 나이  0 평균 거래가 :  22722.186320754718
용산구 아파트 나이  0 의 거래비율 :  3.172465394687617

용산구 아파트 나이  1 의 거래량   :  3447
용산구 아파트 나이  1 평균 거래가 :  50074.91906005222
용산구 아파트 나이  1 의 거래비율 :  25.791245791245792

용산구 아파트 나이  2 의 거래량   :  4324
용산구 아파트 나이  2 평균 거래가 :  65880.2823774283
용산구 아파트 나이  2 의 거래비율 :  32.35316124205013

용산구 아파트 나이  3 의 거래량   :  2960
용산구 아파트 나이  3 평균 거래가 :  97381.26114864864
용산구 아파트 나이  3 의 거래비율 :  22.1473999251777

용산구 아파트 나이  4 의 거래량   :  2210
용산구 아파트 나이  4 평균 거래가 :  170043.09909502263
용산구 아파트 나이  4 의 거래비율 :  16.535727646838758

--------------------------------------------------------------------------------------------------
은평구 의 거래량                  :  21312
은평구 의 힘                      :  2.871134402554275

은평구 아파트 나이  0 의 거래량   :  874
은평구 아파트 나이  0 평균 거래가 :  15185.152173913044
은평구 아파트 나이  0 의 거래비율 :  4.100975975975976

은평구 아파트 나이  1 의 거래량   :  5187
은평구 아파트 나이  1 평균 거래가 :  30006.01137459032
은평구 아파트 나이  1 의 거래비율 :  24.3384009009009

은평구 아파트 나이  2 의 거래량   :  10705
은평구 아파트 나이  2 평균 거래가 :  37147.78944418496
은평구 아파트 나이  2 의 거래비율 :  50.22991741741742

은평구 아파트 나이  3 의 거래량   :  3979
은평구 아파트 나이  3 평균 거래가 :  55557.25735109324
은평구 아파트 나이  3 의 거래비율 :  18.67023273273273

은평구 아파트 나이  4 의 거래량   :  567
은평구 아파트 나이  4 평균 거래가 :  71116.22751322751
은평구 아파트 나이  4 의 거래비율 :  2.660472972972973

--------------------------------------------------------------------------------------------------
강동구 의 거래량                  :  42964
강동구 의 힘                      :  5.788073314158308

강동구 아파트 나이  0 의 거래량   :  1841
강동구 아파트 나이  0 평균 거래가 :  23751.876697447038
강동구 아파트 나이  0 의 거래비율 :  4.284982776277814

강동구 아파트 나이  1 의 거래량   :  13454
강동구 아파트 나이  1 평균 거래가 :  39738.69577820723
강동구 아파트 나이  1 의 거래비율 :  31.31458895819756

강동구 아파트 나이  2 의 거래량   :  21857
강동구 아파트 나이  2 평균 거래가 :  45897.07713775907
강동구 아파트 나이  2 의 거래비율 :  50.872823759426495

강동구 아파트 나이  3 의 거래량   :  5379
강동구 아파트 나이  3 평균 거래가 :  68409.57705893289
강동구 아파트 나이  3 의 거래비율 :  12.519784005213667

강동구 아파트 나이  4 의 거래량   :  433
강동구 아파트 나이  4 평균 거래가 :  79843.47113163973
강동구 아파트 나이  4 의 거래비율 :  1.0078205008844614

--------------------------------------------------------------------------------------------------
강남구 의 거래량                  :  52518
강남구 의 힘                      :  7.075180018456523

강남구 아파트 나이  0 의 거래량   :  6733
강남구 아파트 나이  0 평균 거래가 :  37891.01930788653
강남구 아파트 나이  0 의 거래비율 :  12.820366350584562

강남구 아파트 나이  1 의 거래량   :  12788
강남구 아파트 나이  1 평균 거래가 :  65909.97247419455
강남구 아파트 나이  1 의 거래비율 :  24.34974675349404

강남구 아파트 나이  2 의 거래량   :  18456
강남구 아파트 나이  2 평균 거래가 :  83474.59915474642
강남구 아파트 나이  2 의 거래비율 :  35.14223694733234

강남구 아파트 나이  3 의 거래량   :  9072
강남구 아파트 나이  3 평균 거래가 :  122310.06426366844
강남구 아파트 나이  3 의 거래비율 :  17.27407745915686

강남구 아파트 나이  4 의 거래량   :  5469
강남구 아파트 나이  4 평균 거래가 :  192530.12909124154
강남구 아파트 나이  4 의 거래비율 :  10.413572489432195

--------------------------------------------------------------------------------------------------
종로구 의 거래량                  :  5715
종로구 의 힘                      :  0.769919909468735

종로구 아파트 나이  0 의 거래량   :  609
종로구 아파트 나이  0 평균 거래가 :  15991.76683087028
종로구 아파트 나이  0 의 거래비율 :  10.656167979002625

종로구 아파트 나이  1 의 거래량   :  1474
종로구 아파트 나이  1 평균 거래가 :  30048.244911804613
종로구 아파트 나이  1 의 거래비율 :  25.7917760279965

종로구 아파트 나이  2 의 거래량   :  2310
종로구 아파트 나이  2 평균 거래가 :  47883.43939393939
종로구 아파트 나이  2 의 거래비율 :  40.41994750656168

종로구 아파트 나이  3 의 거래량   :  763
종로구 아파트 나이  3 평균 거래가 :  66245.91087811271
종로구 아파트 나이  3 의 거래비율 :  13.350831146106737

종로구 아파트 나이  4 의 거래량   :  559
종로구 아파트 나이  4 평균 거래가 :  115689.99821109124
종로구 아파트 나이  4 의 거래비율 :  9.781277340332458

--------------------------------------------------------------------------------------------------
마포구 의 거래량                  :  26719
마포구 의 힘                      :  3.599560815589699

마포구 아파트 나이  0 의 거래량   :  1188
마포구 아파트 나이  0 평균 거래가 :  20644.771043771045
마포구 아파트 나이  0 의 거래비율 :  4.446274186908193

마포구 아파트 나이  1 의 거래량   :  9068
마포구 아파트 나이  1 평균 거래가 :  41063.891596823996
마포구 아파트 나이  1 의 거래비율 :  33.938395898050075

마포구 아파트 나이  2 의 거래량   :  11980
마포구 아파트 나이  2 평균 거래가 :  53760.13313856428
마포구 아파트 나이  2 의 거래비율 :  44.83700737303043

마포구 아파트 나이  3 의 거래량   :  3470
마포구 아파트 나이  3 평균 거래가 :  72764.32968299712
마포구 아파트 나이  3 의 거래비율 :  12.987012987012987

마포구 아파트 나이  4 의 거래량   :  1013
마포구 아파트 나이  4 평균 거래가 :  117965.54590325765
마포구 아파트 나이  4 의 거래비율 :  3.791309554998316

--------------------------------------------------------------------------------------------------
노원구 의 거래량                  :  74411
노원구 의 힘                      :  10.02458624382818

노원구 아파트 나이  0 의 거래량   :  7532
노원구 아파트 나이  0 평균 거래가 :  17286.374535315987
노원구 아파트 나이  0 의 거래비율 :  10.122159358159411

노원구 아파트 나이  1 의 거래량   :  39602
노원구 아파트 나이  1 평균 거래가 :  23639.566082521083
노원구 아파트 나이  1 의 거래비율 :  53.22062598271761

노원구 아파트 나이  2 의 거래량   :  22173
노원구 아파트 나이  2 평균 거래가 :  37316.93442475082
노원구 아파트 나이  2 의 거래비율 :  29.798013734528496

노원구 아파트 나이  3 의 거래량   :  4730
노원구 아파트 나이  3 평균 거래가 :  54523.47082452432

노원구 아파트 나이  3 의 거래비율 :  6.356587063740576

노원구 아파트 나이  4 의 거래량   :  374
노원구 아파트 나이  4 평균 거래가 :  58990.0
노원구 아파트 나이  4 의 거래비율 :  0.502613860853906

--------------------------------------------------------------------------------------------------
광진구 의 거래량                  :  15374
광진구 의 힘                      :  2.071172123914669

광진구 아파트 나이  0 의 거래량   :  228
광진구 아파트 나이  0 평균 거래가 :  14543.434210526315
광진구 아파트 나이  0 의 거래비율 :  1.4830232860673864

광진구 아파트 나이  1 의 거래량   :  4325
광진구 아파트 나이  1 평균 거래가 :  39649.81710982659
광진구 아파트 나이  1 의 거래비율 :  28.131911018602835

광진구 아파트 나이  2 의 거래량   :  8470
광진구 아파트 나이  2 평균 거래가 :  55617.09551357733
광진구 아파트 나이  2 의 거래비율 :  55.09301417978405

광진구 아파트 나이  3 의 거래량   :  1170
광진구 아파트 나이  3 평균 거래가 :  80225.05213675214
광진구 아파트 나이  3 의 거래비율 :  7.610251073240536

광진구 아파트 나이  4 의 거래량   :  1181
광진구 아파트 나이  4 평균 거래가 :  111447.516511431
광진구 아파트 나이  4 의 거래비율 :  7.681800442305191

--------------------------------------------------------------------------------------------------
성동구 의 거래량                  :  26087
성동구 의 힘                      :  3.514418316414854

성동구 아파트 나이  0 의 거래량   :  100
성동구 아파트 나이  0 평균 거래가 :  15649.75
성동구 아파트 나이  0 의 거래비율 :  0.38333269444550927

성동구 아파트 나이  1 의 거래량   :  9323
성동구 아파트 나이  1 평균 거래가 :  41150.65322321141
성동구 아파트 나이  1 의 거래비율 :  35.738107103154825

성동구 아파트 나이  2 의 거래량   :  12340
성동구 아파트 나이  2 평균 거래가 :  53140.293273906
성동구 아파트 나이  2 의 거래비율 :  47.30325449457584

성동구 아파트 나이  3 의 거래량   :  3800
성동구 아파트 나이  3 평균 거래가 :  66982.59657894737
성동구 아파트 나이  3 의 거래비율 :  14.566642388929353

성동구 아파트 나이  4 의 거래량   :  524
성동구 아파트 나이  4 평균 거래가 :  163596.27671755725
성동구 아파트 나이  4 의 거래비율 :  2.0086633188944685

--------------------------------------------------------------------------------------------------
성북구 의 거래량                  :  37128
성북구 의 힘                      :  5.00185238823363

성북구 아파트 나이  0 의 거래량   :  155
성북구 아파트 나이  0 평균 거래가 :  15134.76129032258
성북구 아파트 나이  0 의 거래비율 :  0.41747468218056455

성북구 아파트 나이  1 의 거래량   :  15309
성북구 아파트 나이  1 평균 거래가 :  30528.229799464367
성북구 아파트 나이  1 의 거래비율 :  41.23303167420814

성북구 아파트 나이  2 의 거래량   :  16014
성북구 아파트 나이  2 평균 거래가 :  40251.18714874485
성북구 아파트 나이  2 의 거래비율 :  43.13186813186813

성북구 아파트 나이  3 의 거래량   :  5216
성북구 아파트 나이  3 평균 거래가 :  51032.41219325153
성북구 아파트 나이  3 의 거래비율 :  14.048696401637578

성북구 아파트 나이  4 의 거래량   :  434
성북구 아파트 나이  4 평균 거래가 :  72290.89631336405
성북구 아파트 나이  4 의 거래비율 :  1.1689291101055808

--------------------------------------------------------------------------------------------------
서대문구 의 거래량                  :  20131
서대문구 의 힘                      :  2.712031093178496

서대문구 아파트 나이  0 의 거래량   :  594
서대문구 아파트 나이  0 평균 거래가 :  18904.6734006734
서대문구 아파트 나이  0 의 거래비율 :  2.9506730912522974

서대문구 아파트 나이  1 의 거래량   :  7122
서대문구 아파트 나이  1 평균 거래가 :  31100.408733501827
서대문구 아파트 나이  1 의 거래비율 :  35.37827231632805

서대문구 아파트 나이  2 의 거래량   :  9305
서대문구 아파트 나이  2 평균 거래가 :  40892.67716281569
서대문구 아파트 나이  2 의 거래비율 :  46.22224429983607

서대문구 아파트 나이  3 의 거래량   :  2577
서대문구 아파트 나이  3 평균 거래가 :  53353.250291036085
서대문구 아파트 나이  3 의 거래비율 :  12.801152451443048

서대문구 아파트 나이  4 의 거래량   :  533
서대문구 아파트 나이  4 평균 거래가 :  72739.08067542214
서대문구 아파트 나이  4 의 거래비율 :  2.6476578411405294

--------------------------------------------------------------------------------------------------
중구 의 거래량                  :  8313
중구 의 힘                      :  1.1199202462665958

중구 아파트 나이  0 의 거래량   :  229
중구 아파트 나이  0 평균 거래가 :  16377.563318777293
중구 아파트 나이  0 의 거래비율 :  2.7547215205100444

중구 아파트 나이  1 의 거래량   :  2456
중구 아파트 나이  1 평균 거래가 :  37915.51140065146
중구 아파트 나이  1 의 거래비율 :  29.54408757367978

중구 아파트 나이  2 의 거래량   :  3600
중구 아파트 나이  2 평균 거래가 :  51166.78166666667
중구 아파트 나이  2 의 거래비율 :  43.305665824612056

중구 아파트 나이  3 의 거래량   :  1475
중구 아파트 나이  3 평균 거래가 :  69510.60813559323
중구 아파트 나이  3 의 거래비율 :  17.743293636472995

중구 아파트 나이  4 의 거래량   :  553
중구 아파트 나이  4 평균 거래가 :  112403.0054249548
중구 아파트 나이  4 의 거래비율 :  6.652231444725129

--------------------------------------------------------------------------------------------------
관악구 의 거래량                  :  23504
관악구 의 힘                      :  3.1664387667809533

관악구 아파트 나이  0 의 거래량   :  1285
관악구 아파트 나이  0 평균 거래가 :  16571.85758754864
관악구 아파트 나이  0 의 거래비율 :  5.46715452688904

관악구 아파트 나이  1 의 거래량   :  8977
관악구 아파트 나이  1 평균 거래가 :  29806.50651665367
관악구 아파트 나이  1 의 거래비율 :  38.19349897889721

관악구 아파트 나이  2 의 거래량   :  9768
관악구 아파트 나이  2 평균 거래가 :  39772.70608108108
관악구 아파트 나이  2 의 거래비율 :  41.55888359428182

관악구 아파트 나이  3 의 거래량   :  3290
관악구 아파트 나이  3 평균 거래가 :  48920.87659574468
관악구 아파트 나이  3 의 거래비율 :  13.997617426820966

관악구 아파트 나이  4 의 거래량   :  184
관악구 아파트 나이  4 평균 거래가 :  61664.663043478264
관악구 아파트 나이  4 의 거래비율 :  0.7828454731109599

--------------------------------------------------------------------------------------------------
서초구 의 거래량                  :  37521
서초구 의 힘                      :  5.05479701192938

서초구 아파트 나이  0 의 거래량   :  1684
서초구 아파트 나이  0 평균 거래가 :  24036.902612826605
서초구 아파트 나이  0 의 거래비율 :  4.488153300818208

서초구 아파트 나이  1 의 거래량   :  5823
서초구 아파트 나이  1 평균 거래가 :  58194.55744461618
서초구 아파트 나이  1 의 거래비율 :  15.519309186855361

서초구 아파트 나이  2 의 거래량   :  14825
서초구 아파트 나이  2 평균 거래가 :  82482.7489376054
서초구 아파트 나이  2 의 거래비율 :  39.5112070573812

서초구 아파트 나이  3 의 거래량   :  9000
서초구 아파트 나이  3 평균 거래가 :  105822.86755555555
서초구 아파트 나이  3 의 거래비율 :  23.986567522187574

서초구 아파트 나이  4 의 거래량   :  6189
서초구 아파트 나이  4 평균 거래가 :  155667.83842300856
서초구 아파트 나이  4 의 거래비율 :  16.494762932757656

--------------------------------------------------------------------------------------------------
동작구 의 거래량                  :  27862
동작구 의 힘                      :  3.7535447974834466

동작구 아파트 나이  0 의 거래량   :  495
동작구 아파트 나이  0 평균 거래가 :  18179.646464646463
동작구 아파트 나이  0 의 거래비율 :  1.7766133084487832

동작구 아파트 나이  1 의 거래량   :  7869
동작구 아파트 나이  1 평균 거래가 :  37274.17054263566
동작구 아파트 나이  1 의 거래비율 :  28.242767927643385

동작구 아파트 나이  2 의 거래량   :  13976
동작구 아파트 나이  2 평균 거래가 :  52616.25207498569
동작구 아파트 나이  2 의 거래비율 :  50.16151030076807

동작구 아파트 나이  3 의 거래량   :  4918
동작구 아파트 나이  3 평균 거래가 :  66727.42537616918
동작구 아파트 나이  3 의 거래비율 :  17.65128131505276

동작구 아파트 나이  4 의 거래량   :  604
동작구 아파트 나이  4 평균 거래가 :  86258.57947019867
동작구 아파트 나이  4 의 거래비율 :  2.1678271480870004

--------------------------------------------------------------------------------------------------
동대문구 의 거래량                  :  24950
동대문구 의 힘                      :  3.361242649386691

동대문구 아파트 나이  0 의 거래량   :  1352
동대문구 아파트 나이  0 평균 거래가 :  16804.6050295858
동대문구 아파트 나이  0 의 거래비율 :  5.4188376753507015

동대문구 아파트 나이  1 의 거래량   :  7330
동대문구 아파트 나이  1 평균 거래가 :  31739.442428376537
동대문구 아파트 나이  1 의 거래비율 :  29.37875751503006

동대문구 아파트 나이  2 의 거래량   :  12161
동대문구 아파트 나이  2 평균 거래가 :  39779.06290601102
동대문구 아파트 나이  2 의 거래비율 :  48.741482965931866

동대문구 아파트 나이  3 의 거래량   :  3863
동대문구 아파트 나이  3 평균 거래가 :  48143.88894641471
동대문구 아파트 나이  3 의 거래비율 :  15.482965931863728

동대문구 아파트 나이  4 의 거래량   :  244
동대문구 아파트 나이  4 평균 거래가 :  57760.9631147541
동대문구 아파트 나이  4 의 거래비율 :  0.9779559118236473

--------------------------------------------------------------------------------------------------
영등포구 의 거래량                  :  31875
영등포구 의 힘                      :  4.294172723414861

영등포구 아파트 나이  0 의 거래량   :  1642
영등포구 아파트 나이  0 평균 거래가 :  14312.243605359317
영등포구 아파트 나이  0 의 거래비율 :  5.151372549019608

영등포구 아파트 나이  1 의 거래량   :  9979
영등포구 아파트 나이  1 평균 거래가 :  32386.230884858203
영등포구 아파트 나이  1 의 거래비율 :  31.30666666666667

영등포구 아파트 나이  2 의 거래량   :  15153
영등포구 아파트 나이  2 평균 거래가 :  45415.04969313007
영등포구 아파트 나이  2 의 거래비율 :  47.538823529411765

영등포구 아파트 나이  3 의 거래량   :  3492
영등포구 아파트 나이  3 평균 거래가 :  73179.9919816724
영등포구 아파트 나이  3 의 거래비율 :  10.955294117647059

영등포구 아파트 나이  4 의 거래량   :  1609
영등포구 아파트 나이  4 평균 거래가 :  112058.0826600373
영등포구 아파트 나이  4 의 거래비율 :  5.047843137254902

--------------------------------------------------------------------------------------------------
도봉구 의 거래량                  :  33906
도봉구 의 힘                      :  4.567787305415036

도봉구 아파트 나이  0 의 거래량   :  2664
도봉구 아파트 나이  0 평균 거래가 :  13729.076576576577
도봉구 아파트 나이  0 의 거래비율 :  7.857016457264201

도봉구 아파트 나이  1 의 거래량   :  12771
도봉구 아파트 나이  1 평균 거래가 :  21840.46691723436

도봉구 아파트 나이  1 의 거래비율 :  37.66589984073615

도봉구 아파트 나이  2 의 거래량   :  16085
도봉구 아파트 나이  2 평균 거래가 :  32238.300093254584
도봉구 아파트 나이  2 의 거래비율 :  47.439981124284785

도봉구 아파트 나이  3 의 거래량   :  2133
도봉구 아파트 나이  3 평균 거래가 :  51675.899671823725
도봉구 아파트 나이  3 의 거래비율 :  6.290921960714917

도봉구 아파트 나이  4 의 거래량   :  253
도봉구 아파트 나이  4 평균 거래가 :  58902.56916996047
도봉구 아파트 나이  4 의 거래비율 :  0.746180616999941

--------------------------------------------------------------------------------------------------
중랑구 의 거래량                  :  23495
중랑구 의 힘                      :  3.1652262944825775

중랑구 아파트 나이  0 의 거래량   :  2673
중랑구 아파트 나이  0 평균 거래가 :  16215.575009352788
중랑구 아파트 나이  0 의 거래비율 :  11.376888699723345

중랑구 아파트 나이  1 의 거래량   :  7527
중랑구 아파트 나이  1 평균 거래가 :  25103.151587617907
중랑구 아파트 나이  1 의 거래비율 :  32.036603532666525

중랑구 아파트 나이  2 의 거래량   :  10895
중랑구 아파트 나이  2 평균 거래가 :  34058.35089490592
중랑구 아파트 나이  2 의 거래비율 :  46.371568418812515

중랑구 아파트 나이  3 의 거래량   :  2343
중랑구 아파트 나이  3 평균 거래가 :  47681.763124199744
중랑구 아파트 나이  3 의 거래비율 :  9.972334539263674

중랑구 아파트 나이  4 의 거래량   :  57
중랑구 아파트 나이  4 평균 거래가 :  72504.73684210527
중랑구 아파트 나이  4 의 거래비율 :  0.2426048095339434

--------------------------------------------------------------------------------------------------
양천구 의 거래량                  :  37218
양천구 의 힘                      :  5.01397711121739

양천구 아파트 나이  0 의 거래량   :  78
양천구 아파트 나이  0 평균 거래가 :  13830.641025641025
양천구 아파트 나이  0 의 거래비율 :  0.20957601160728678

양천구 아파트 나이  1 의 거래량   :  11637
양천구 아파트 나이  1 평균 거래가 :  32047.81747873163
양천구 아파트 나이  1 의 거래비율 :  31.26712880864098

양천구 아파트 나이  2 의 거래량   :  18949
양천구 아파트 나이  2 평균 거래가 :  49116.969655390785
양천구 아파트 나이  2 의 거래비율 :  50.91353646085228

양천구 아파트 나이  3 의 거래량   :  5015
양천구 아파트 나이  3 평균 거래가 :  79446.43010967098
양천구 아파트 나이  3 의 거래비율 :  13.474662797571067

양천구 아파트 나이  4 의 거래량   :  1539
양천구 아파트 나이  4 평균 거래가 :  116236.37751786875
양천구 아파트 나이  4 의 거래비율 :  4.135095921328389

--------------------------------------------------------------------------------------------------
강북구 의 거래량                  :  13354
강북구 의 힘                      :  1.7990394525013977

강북구 아파트 나이  0 의 거래량   :  202
강북구 아파트 나이  0 평균 거래가 :  11643.836633663366
강북구 아파트 나이  0 의 거래비율 :  1.5126553841545605

강북구 아파트 나이  1 의 거래량   :  4996
강북구 아파트 나이  1 평균 거래가 :  27204.074459567655
강북구 아파트 나이  1 의 거래비율 :  37.41201138235735

강북구 아파트 나이  2 의 거래량   :  6700
강북구 아파트 나이  2 평균 거래가 :  35141.18417910448
강북구 아파트 나이  2 의 거래비율 :  50.17223303878988

강북구 아파트 나이  3 의 거래량   :  1422
강북구 아파트 나이  3 평균 거래가 :  44625.1652601969
강북구 아파트 나이  3 의 거래비율 :  10.648494833008836

강북구 아파트 나이  4 의 거래량   :  34
강북구 아파트 나이  4 평균 거래가 :  43116.17647058824
강북구 아파트 나이  4 의 거래비율 :  0.25460536168938147

In [91]:
train[['gu', 'gu_mean']].drop_duplicates().sort_values(by = ['gu_mean'], ascending = False)

          gu  gu_mean
512104   서초구    93760
222204   강남구    91419
144563   용산구    84635
0        송파구    69447
381567   광진구    56678
480287    중구    53622
396941   성동구    52947
280437   마포구    52881
549625   동작구    50892
691713   양천구    50568
274722   종로구    48969
179240   강동구    46180
602437  영등포구    46140
460156  서대문구    39218
157928   은평구    38850
423028   성북구    38026
577487  동대문구    37643
100677   강서구    36881
488600   관악구    36150
51773    구로구    33590
728931   강북구    32847
668218   중랑구    30611
307156   노원구    29213
634312   도봉구    28289
88634    금천구    28286

In [140]:
asd = pd.DataFrame(b, c)
asd.sort_values(by = [0], ascending = False)

            0
서초구   83800.0
강남구   80000.0
용산구   69000.0
송파구   62500.0
광진구   52500.0
중구    50800.0
동작구   49300.0
마포구   49000.0
성동구   49000.0
양천구   44000.0
강동구   43000.0
종로구   42000.0
영등포구  40200.0
성북구   37000.0
서대문구  37000.0
은평구   36950.0
동대문구  36900.0
관악구   36000.0
강서구   34000.0
강북구   32800.0
구로구   32300.0
중랑구   29950.0
금천구   28000.0
도봉구   26800.0
노원구   26500.0

In [93]:
train.corr()['transaction_real_price']

exclusive_use_area          0.668717
year_of_completion         -0.005060
floor                       0.142295
transaction_real_price      1.000000
hanriver                    0.286348
transaction_year            0.115091
hakgun                      0.220111
exclusive_use_area_group    0.603305
hakgun_rank                -0.518919
year_of_completion_group   -0.006486
park_gaesu                 -0.241588
pop                         0.076535
gu_area                     0.267520
diff_year                   0.041220
rebuilding                  0.239557
river_re                    0.321551
gu_mean                     0.595677
apt_age_group               0.040671
dep_shop                    0.325747
강남과의 거리                    -0.485249
kangnam                    -0.456580
age_group_rate             -0.106686
Name: transaction_real_price, dtype: float64

In [82]:
train["age_group_rate"] = 0
train['age_group_rate'] = np.where( train['age_group_rate'] == 40, , train['age_group_rate'])

train['age_group_rate'] = np.where( train['age_group_rate'] == 50, 0.21508291258923348, train['age_group_rate'])

In [83]:
gajung2=train.groupby(["gu","age_group_rate"])["apt_age_group"].count()
gajung2 = pd.DataFrame(gajung2)

gajung2

                     apt_age_group
gu   age_group_rate
강남구  0.000000                13563
     0.137435                12514
     0.144424                11248
     0.173756                14968
     0.262330                  225
강동구  0.000000                14459
     0.137435                 8353
     0.144424                 8510
     0.173756                11642
강북구  0.000000                 6024
     0.137435                 1905
     0.144424                    8
     0.173756                 5409
     0.262330                    8
강서구  0.000000                14215
     0.137435                10158
     0.144424                   94
     0.173756                19360
     0.262330                   59
관악구  0.000000                 8760
     0.137435                 2694
     0.144424                  636
     0.173756                11036
     0.262330                  378
광진구  0.000000                 3526
     0.137435                 3795
     0.144424                  506
     0.173756                 7484
     0.262330                   63
구로구  0.000000                11054
     0.137435                 5937
     0.144424                 1001
     0.173756                18767
     0.215083                   10
     0.262330                   92
금천구  0.000000                 3663
     0.137435                 1760
     0.144424                  877
     0.173756                 5732
     0.262330                   11
노원구  0.000000                 5662
     0.137435                39782
     0.144424                 1698
     0.173756                27255
     0.262330                   14
도봉구  0.000000                 3620
     0.137435                17120
     0.144424                  404
     0.173756                12762
동대문구 0.000000                11802
     0.137435                 2046
     0.144424                  762
     0.173756                10315
     0.262330                   25
동작구  0.000000                10526
     0.137435                 5944
     0.144424                  223
     0.173756                11159
     0.262330                   10
마포구  0.000000                11859
     0.137435                 2505
     0.144424                  593
     0.173756                11573
     0.262330                  189
서대문구 0.000000                 6825
     0.137435                 2941
     0.144424                  461
     0.173756                 9539
     0.262330                  365
서초구  0.000000                13429
     0.137435                 6116
     0.144424                 7609
     0.173756                 9743
     0.262330                  624
성동구  0.000000                 8216
     0.137435                 3672
     0.144424                  820
     0.173756                13312
     0.262330                   67
성북구  0.000000                18328
     0.137435                  756
     0.144424                  332
     0.173756                17509
     0.262330                  203
송파구  0.000000                17486
     0.137435                13850
     0.144424                 8486
     0.173756                11951
양천구  0.000000                 9113
     0.137435                13264
     0.144424                 1852
     0.173756                12989
영등포구 0.000000                 6984
     0.137435                 5524
     0.144424                 3853
     0.173756                14288
     0.262330                 1226
용산구  0.000000                 4095
     0.137435                  806
     0.144424                 1414
     0.173756                 5895
     0.262330                 1155
은평구  0.000000                14550
     0.137435                 1784
     0.144424                   29
     0.173756                 4899
     0.262330                   50
종로구  0.000000                 2621
     0.137435                  737
     0.144424                   90
     0.173756                 2120
     0.215083                   10
     0.262330                  137
중구   0.000000                 4078
     0.137435                  337
     0.144424                  111
     0.173756                 3586
     0.215083                    2
     0.262330                  199
중랑구  0.000000                 6227
     0.137435                 4706
     0.144424                  105
     0.173756                12406
     0.262330                   51

In [84]:
a = []
b = []
for j in train['gu'].unique():
    gajung2_yc=gajung2.loc[j]
    gajung2_yc=gajung2_yc.reset_index()
    # gajung_gn

    gagung2_sum=0
    sum2 = 0
    sum1=0

    for i in range(len(gajung2_yc["age_group_rate"])) : 


        sum1 = gajung2_yc["age_group_rate"][i] * gajung2_yc["apt_age_group"][i]
        gagung2_sum = gagung2_sum + sum1

        sum2 = sum2+ gajung2_yc["apt_age_group"][i]

    gagung2_avg_yc = gagung2_sum / sum2

    a.append(j)
    b.append(gagung2_avg_yc)
#     print(j, gagung2_avg_yc)
#     print('')

In [87]:
data = pd.DataFrame(b, a)
data.sort_values(by = [0], ascending = False)

             0
노원구   0.140464
도봉구   0.136516
영등포구  0.129252
광진구   0.124337
용산구   0.122879
중랑구   0.120491
양천구   0.116807
구로구   0.115235
강남구   0.114325
금천구   0.113543
성동구   0.113225
서대문구  0.110476
강서구   0.109124
관악구   0.105464
강동구   0.102409
서초구   0.101172
송파구   0.100547
동작구   0.100161
마포구   0.093206
종로구   0.091118
강북구   0.090229
중구    0.088785
동대문구  0.087779
성북구   0.087465
은평구   0.052258

In [62]:
train

,gu,dong,apt,exclusive_use_area,year_of_completion,floor,transaction_real_price,hanriver,transaction_year,hakgun,exclusive_use_area_group,hakgun_rank,year_of_completion_group,park_gaesu,pop,gu_area,diff_year,rebuilding,river_re,강남과의 거리,kangnam,dep_shop,gu_mean,apt_age_group
647634,송파구,가락동,시영1,51.4000,1980,4,69000,0,2008,6,1,3,1980,0,676580,33.88,28,0,1,4.354,2,1,69447,20
647635,송파구,가락동,시영1,40.0900,1980,5,55000,0,2008,6,1,3,1980,0,676580,33.88,28,0,1,4.354,2,1,69447,20
647636,송파구,가락동,가락(1차)쌍용아파트,84.6900,1997,1,52500,0,2008,6,2,3,1990,0,676580,33.88,11,0,1,4.354,2,1,69447,10
647637,송파구,가락동,가락한일유앤아이,100.9500,2003,7,39500,0,2008,6,3,3,2000,1,676580,33.88,5,0,1,4.354,2,1,69447,0
647638,송파구,가락동,시영1,51.4000,1980,4,56200,0,2008,6,1,3,1980,0,676580,33.88,28,0,1,4.354,2,1,69447,20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13940,중구,흥인동,동대문 와이즈 캐슬,15.5500,2014,8,16900,0,2017,5,0,2,2010,0,134593,9.96,3,0,1,9.382,7,3,53622,0
13941,중구,흥인동,동대문 와이즈 캐슬,16.5500,2014,10,17000,0,2017,5,0,2,2010,0,134593,9.96,3,0,1,9.382,7,3,53622,0
13942,중구,흥인동,동대문 와이즈 캐슬,22.0700,2014,10,21200,0,2017,5,0,2,2010,0,134593,9.96,3,0,1,9.382,7,3,53622,0
13943,중구,흥인동,청계천 두산위브더제니스,147.3212,2014,16,107000,0,2017,5,4,2,2010,0,134593,9.96,3,0,1,9.382,7,3,53622,0
14012,중구,흥인동,동대문 와이즈 캐슬,15.5500,2014,14,17000,0,2017,5,0,2,2010,0,134593,9.96,3,0,1,9.382,7,3,53622,0

In [71]:
train.to_csv('data/real_train.csv', encoding = 'euc-kr')

In [64]:
len(train['gu_mean'].unique())

25

In [74]:
train.corr()['transaction_real_price']

exclusive_use_area          0.668717
year_of_completion         -0.005060
floor                       0.142295
transaction_real_price      1.000000
hanriver                    0.286348
transaction_year            0.115091
hakgun                      0.220111
exclusive_use_area_group    0.603305
hakgun_rank                -0.518919
year_of_completion_group   -0.006486
park_gaesu                 -0.241588
pop                         0.076535
gu_area                     0.267520
diff_year                   0.041220
rebuilding                  0.239557
river_re                    0.321551
gu_mean                     0.595677
apt_age_group               0.040671
dep_shop                    0.325747
강남과의 거리                    -0.485249
kangnam                    -0.456580
Name: transaction_real_price, dtype: float64

# 아파트 나이와 아파트거래수을 비교해서 가격과 연관성
<!-- 나이와 판매가격을 통해서 얼마나 연관성이 있는지 -->
<!-- 30 40년이 크다 -->
<!-- 수치화 -->
<!-- 구별로 가격, 수 ->  -->
<!-- 구별 아파트 나이 -->
<!-- 구별 매물 수가 다름 -->